name: 15a - Inyección de código
on:
  issues: 
    types:
      - opened
jobs:
  inyeccion:
    runs-on: ubuntu-latest
    env:
      ISSUE_TITLE: ${{ github.event.issue.title }}
    steps:
      - run: |
          echo ${env.ISSUE_TITLE}

