name: 15c - Otros repositorios
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  listar-repos:
    name: Listar repos
    runs-on: ubuntu-latest
    steps:
    - name: List repos
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh repo list ${{ github.repository_owner }} --visibility private
    - name: View repos
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh repo view ${{ github.repository_owner }}/gha-composite-action